name: DISCLib CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.6.0
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.0'
      - name: Install pytest
        run: pip install pytest
      - name: Run tests
        run: pytest Test/