name: DISCLib CI

on: [push]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.6.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.7'
      - name: Install pytest
        run: pip install pytest
      - name: Install pylint
        run: pip install pylint
      - name: Check Python syntax
        run: pylint **/*.py
      - name: Run tests
        run: pytest Test/